development:
  adapter: postgresql
  encoding: unicode
  database: chatter_dev
  port: 5432
  pool: 5
  username: swidjit
  password: password
  min_messages: warning
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: chatter_dev
  pool: 5
  username: acolket
  password: BNAZ0he7leqKfAoe
  min_messages: warning
  host: localhost
